export type SampleDataItem = {
  id: number;
  slug: string;
  src: string;
  title: string;
  note: string;
  date: string;
  location: string;
  images: string[];
};

export type SampleDataType = SampleDataItem[];
export const sampleData: SampleDataType = [
  {
    id: 1,
    slug: "NewYorkPenthouse",
    src: "/assets/Cozy1.jpeg",
    title: "New York Penthouse",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2022",
    images: [
      "/assets/Cozy2.jpeg",
      "/assets/Cozy3.jpeg",
      "/assets/Cozy4.jpeg",
      "/assets/Cozy5.jpeg",
      "/assets/Cozy6.jpeg",
    ],
  },
  {
    id: 2,
    slug: "ChelseaLoft",
    src: "/assets/Coastal1.jpeg",
    title: "Chelsea Loft",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2023",
    images: [
      "/assets/Coastal2.jpeg",
      "/assets/Coastal3.jpeg",
      "/assets/Coastal4.jpeg",
      "/assets/Coastal5.jpeg",
      "/assets/Coastal6.jpeg",
    ],
  },
  {
    id: 3,
    slug: "TheMarloweResidence",
    src: "/assets/Room1.jpeg",
    title: "The Marlowe Residence",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2025",
    images: [
      "/assets/Room2.jpeg",
      "/assets/Room3.jpeg",
      "/assets/Room4.jpeg",
      "/assets/Room5.jpeg",
      "/assets/Room6.jpeg",
    ],
  },

  {
    id: 3,
    slug: "PacificHeightsVilla",
    src: "/assets/Vibrant1.jpeg",
    title: "Pacific Heights Villa",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2018",
    images: [
      "/assets/Vibrant2.jpeg",
      "/assets/Vibrant3.jpeg",
      "/assets/Vibrant4.jpeg",
      "/assets/Vibrant5.jpeg",
      "/assets/Vibrant6.jpeg",
    ],
  },
  {
    id: 4,
    slug: "Astoria1",
    src: "/assets/Astoria1.jpeg",
    title: "The Astoria",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2019",
    images: [
      "/assets/Astoria2.jpeg",
      "/assets/Astoria3.jpeg",
      "/assets/Astoria4.jpeg",
      "/assets/Astoria5.jpeg",
      "/assets/Astoria6.jpeg",
    ],
  },

  {
    id: 5,
    slug: "SohoTownhouse",
    src: "/assets/Townhouse1.jpeg",
    title: "Soho Townhouse",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2022",
    images: [
      "/assets/Townhouse2.jpeg",
      "/assets/Townhouse3.jpeg",
      "/assets/Townhouse4.jpeg",
      "/assets/Townhouse5.jpeg",
      "/assets/Townhouse6.jpeg",
    ],
  },

  {
    id: 6,
    slug: "BeverlyHillsHaven",
    src: "/assets/Beverl1.jpeg",
    title: "Beverl yHills Haven",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2020",
    images: [
      "/assets/Beverl2.jpeg",
      "/assets/Beverl3.jpeg",
      "/assets/Beverl4.jpeg",
      "/assets/Beverl7.jpeg",
      "/assets/Beverl6.jpeg",
    ],
  },

  {
    id: 3,
    slug: "PacificHeightsVilla",
    src: "/assets/Vibrant1.jpeg",
    title: "Pacific Heights Villa",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2018",
    images: [
      "/assets/Vibrant2.jpeg",
      "/assets/Vibrant3.jpeg",
      "/assets/Vibrant4.jpeg",
      "/assets/Vibrant5.jpeg",
      "/assets/Vibrant6.jpeg",
    ],
  },
  {
    id: 4,
    slug: "Astoria1",
    src: "/assets/Astoria1.jpeg",
    title: "The Astoria",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2019",
    images: [
      "/assets/Astoria2.jpeg",
      "/assets/Astoria3.jpeg",
      "/assets/Astoria4.jpeg",
      "/assets/Astoria5.jpeg",
      "/assets/Astoria6.jpeg",
    ],
  },
  {
    id: 3,
    slug: "PacificHeightsVilla",
    src: "/assets/Vibrant1.jpeg",
    title: "Pacific Heights Villa",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2018",
    images: [
      "/assets/Vibrant2.jpeg",
      "/assets/Vibrant3.jpeg",
      "/assets/Vibrant4.jpeg",
      "/assets/Vibrant5.jpeg",
      "/assets/Vibrant6.jpeg",
    ],
  },
  {
    id: 4,
    slug: "Astoria1",
    src: "/assets/Astoria1.jpeg",
    title: "The Astoria",
    note: "more info",
    location: "Maguelone (FR)",
    date: "2019",
    images: [
      "/assets/Astoria2.jpeg",
      "/assets/Astoria3.jpeg",
      "/assets/Astoria4.jpeg",
      "/assets/Astoria5.jpeg",
      "/assets/Astoria6.jpeg",
    ],
  },

  //   {
  //     id: 1,
  //     slug: "New York Penthouse",
  //     src: "/assets/Cozy2.jpeg",
  //     title: "New York Penthouse",
  //     note: "more info",
  //     location: "Maguelone (FR)",
  //     date: "2023",
  //   },
  //   {
  //     id: 1,
  //     slug: "New York Penthouse",
  //     src: "/assets/Cozy3.jpeg",
  //     title: "New York Penthouse",
  //     note: "more info",
  //     location: "Maguelone (FR)",
  //     date: "2023",
  //   },
  //   {
  //     id: 1,
  //     slug: "New York Penthouse",
  //     src: "/assets/Cozy4.jpeg",
  //     title: "New York Penthouse",
  //     note: "more info",
  //     location: "Maguelone (FR)",
  //     date: "2023",
  //   },
  //   {
  //     id: 1,
  //     slug: "New York Penthouse",
  //     src: "/assets/Cozy5.jpeg",
  //     title: "New York Penthouse",
  //     note: "more info",
  //     location: "Maguelone (FR)",
  //     date: "2023",
  //   },
  //   {
  //     id: 1,
  //     slug: "New York Penthouse",
  //     src: "/assets/Cozy6.jpeg",
  //     title: "New York Penthouse",
  //     note: "more info",
  //     location: "Maguelone (FR)",
  //     date: "2023",
  //   },
];
