import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header } from "@/sections/Header";
import { ViewTransitions } from "next-view-transitions";

const ppneuemontreal = localFont({
  src: [
    {
      path: "./font/ppneuemontreal-medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/ppneuemontreal-bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-ppneuemontreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${ppneuemontreal.variable} antialiased font-ppneuemontreal`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
